/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface EmbeddingPayload {
  documentPath: string;
  start: number;
  end: number;
  content: string;
}

export interface EmbeddingWithPayload {
  embedding: Array<number>;
  payload: EmbeddingPayload;
  id: number;
}

export interface ResultWithScore {
  content: string;
  documentPath: string;
  score: number;
}

export declare function search(
  queryEmbedding: Array<number>,
  documentPaths?: Array<string> | undefined | null,
  limit?: number | undefined | null,
  scoreThreshold?: number | undefined | null,
): Array<ResultWithScore>;

export declare function upsertEmbeddings(
  embeddings: Array<EmbeddingWithPayload>,
): void;
